#!/bin/bash

DOTFILE_DIR="$(cd "$(dirname "$1")" || exit; pwd)"
OS=$(uname)

link_file() {
  if [ -f "$2" ] && [ ! -L "$2" ]; then
    echo Removing file "$2"
    rm "$2"
  fi
  echo Linking "$2"
  ln -sf "$DOTFILE_DIR/$1" "$2"
}

# Zsh

link_file .zshrc "$HOME/.zshrc"

# Git configuration

link_file .gitconfig "$HOME/.gitconfig"
link_file .gitconfig.user.shopify "$HOME/.gitconfig.user.shopify"

if [ "$SPIN" ]; then
  link_file .gitconfig.credential.spin "$HOME/.gitconfig.credential"
else
  link_file .gitconfig.credential.macos "$HOME/.gitconfig.credential"
fi

link_file .gitconfig.credential.dev "$HOME/.gitconfig.credential.dev"
link_file .gitconfig "$HOME/.gitignore"

# Software dependencies

if [ "$OS" == "Darwin" ]; then
  brew bundle --file="$DOTFILE_DIR/Brewfile"
fi