#!/bin/bash

this_dir="$(cd "$(dirname "$1")" || exit; pwd)/$(basename "$1")"

link_file() {
  if [ -f "$2" ] && [ ! -L "$2" ]; then
    echo Removing file "$2"
    rm "$2"
  fi
  echo Linking "$2"
  ln -sf "$this_dir$1" "$2"
}

# Link dotfiles
link_file zshrc ~/.zshrc

if [ "$SPIN" ]; then
  echo "This only runs in spin"
fi